### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [jsharris1229/prj-rev-bwfs-dasmoto#3]
https://github.com/jsharris1229/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L1-L35

Your CSS is short, clean and succinct -- good job! One area of improvement is to make sure to comment your main stylings so that it's very clear what each styling represents -- this is a practice that many people forget to do but it goes a long way! Here is a quick reminder of commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/32868971-97e38f72-ca42-11e7-88b3-1c0291373b8e.png">

**Comment by jsharris1229** [comment]
Thank you! I'll work on style comments.
